name: publish
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Update curso python
        run: python3 fix_tags.py
      - name: Publish to lists.sh
        uses: picosh/scp-publish-action@main
        with:
          user: guiosoft
          key: ${{ secrets.PRIVATE_KEY }}
          host: prose.sh
          src: '*.md'
